// This file is part of V-REP, the Virtual Robot Experimentation Platform.
// 
// Copyright 2006-2014 Coppelia Robotics GmbH. All rights reserved. 
// marc@coppeliarobotics.com
// www.coppeliarobotics.com
// 
// V-REP is dual-licensed, under the terms of EITHER (at your option):
//   1. V-REP commercial license (contact us for details)
//   2. GNU GPL (see below)
// 
// GNU GPL license:
// -------------------------------------------------------------------
// V-REP is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// V-REP IS DISTRIBUTED "AS IS", WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTY. THE USER WILL USE IT AT HIS/HER OWN RISK. THE ORIGINAL
// AUTHORS AND COPPELIA ROBOTICS GMBH WILL NOT BE LIABLE FOR DATA LOSS,
// DAMAGES, LOSS OF PROFITS OR ANY OTHER KIND OF LOSS WHILE USING OR
// MISUSING THIS SOFTWARE.
// 
// See the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with V-REP.  If not, see <http://www.gnu.org/licenses/>.
// -------------------------------------------------------------------
//
// This file was automatically created for V-REP release V3.1.2 on June 16th 2014

// This file needs some serious reworking!

#pragma once


#define SIM_API_CALL_NO_ERROR "No error."
#define SIM_LUA_CALL_NO_ERROR "No error."

// Default layers for 3D objects:

// LAYER1
#define SHAPE_LAYER				0x0001

// LAYER2
#define JOINT_LAYER				0x0002

// LAYER3
#define DUMMY_LAYER				0x0004

// LAYER4
#define PROXIMITY_SENSOR_LAYER			0x0008
#define VISION_SENSOR_LAYER	0x0008
#define	MILL_LAYER				0x0008
#define	FORCE_SENSOR_LAYER		0x0008

// LAYER5
#define CAMERA_LIGHT_LAYER		0x0010

// LAYER6
#define GRAPH_LAYER				0x0020
#define PATH_LAYER				0x0020

// LAYER7
#define VOLUME_LAYER			0x0040

// LAYER8
#define ENVIRONMENT_LAYER		0x0080


enum {	GENERAL_PROPERTIES_DLG=0,
		SHAPE_DLG,
		SHAPE_DYN_DLG,
		CAMERA_DLG,
		JOINT_DLG,
		JOINT_DYN_DLG,
		SETTINGS_DLG,
		SELECTION_DLG,
		ENVIRONMENT_DLG,
		COLLISION_DLG,
		PROXIMITY_SENSOR_DLG,
		DETECTION_VOLUME_DLG,
		VISION_SENSOR_DLG,
		VISION_SENSOR_FILTER_DLG,
		MILL_DLG,
		SHAPE_EDITION_DLG,
		OBJECT_DLG,
		CALCULATION_DLG,
		FORCE_SENSOR_DLG,
		GRAPH_DLG,
		BUTTON_DLG,
		CUSTOM_UI_DLG,
		TRANSLATION_ROTATION_DLG,
		LUA_SCRIPT_DLG,
		COLLECTION_DLG,
		DISTANCE_DLG,
		HIERARCHY_DLG,
		BROWSER_DLG,
		IK_DLG,
		DUMMY_DLG,
		LAYERS_DLG,
		DYNAMICS_DLG,
		PATH_DLG,
		PATH_PLANNING_DLG,
		CONSTRAINT_SOLVER_DLG,
		SIMULATION_DLG,
		FOG_DLG,
		TRANSFORMATIONS_DLG,
		MATERIAL_DLG,
		COLOR_DLG,
		PATH_SHAPING_DLG,
		PATH_EDITION_DLG,
		AVI_RECORDER_DLG,
		LIGHT_DLG,
		MIRROR_DLG,
		TEXTURE_DLG,
		GEOMETRY_DLG,
};

enum {	FILE_FORMAT_OBJ=0,
		FILE_FORMAT_DXF,
		FILE_FORMAT_3DS,
		FILE_FORMAT_ASCII_STL,
		FILE_FORMAT_BINARY_STL,
		FILE_FORMAT_COLLADA,
		FILE_FORMAT_ANY_STL,
};

enum {SCRIPT_EXECUTION_ORDER_FIRST=0,
	SCRIPT_EXECUTION_ORDER_NORMAL,
	SCRIPT_EXECUTION_ORDER_LAST
};

enum { // CURSORS:
	sim_cursor_arrow=0,
	sim_cursor_finger,
	sim_cursor_all_directions,
	sim_cursor_horizontal_directions,
	sim_cursor_vertical_directions,
	sim_cursor_slash_directions,
	sim_cursor_backslash_directions,
};

enum { // DATA STREAM TRANSFORMATIONS:
	DATA_STREAM_ORIGINAL=0,
	DATA_STREAM_DERIVATIVE,
	DATA_STREAM_INTEGRAL,
	DATA_STREAM_CUMULATIVE,
};

enum { // RENDERING MODES:
	RENDERING_MODE_SOLID=0,
	RENDERING_MODE_WIREFRAME_EDGES,
	RENDERING_MODE_WIREFRAME_TRIANGLES,
	RENDERING_MODE_BOUNDINGBOX_SOLID,
	RENDERING_MODE_BOUNDINGBOX_WIREFRAME,
};

enum { // TEXTURE COORDINATES MODES (serialized!):
	TEXTURE_COORD_PLANE=0,
	TEXTURE_COORD_CYLINDER,
	TEXTURE_COORD_SPHERE,
	TEXTURE_COORD_CUBE,
};

enum { // catch elements:
	sim_left_button		=0x0001,
	sim_middleButton	=0x0002,
	sim_right_button	=0x0004,
	sim_focus			=0x0008,
};

// Specific camera orientations:
enum {	NO_SPECIFIC_VIEW=0,
		POSITIVE_X_VIEW,
		NEGATIVE_X_VIEW,
		POSITIVE_Y_VIEW,
		NEGATIVE_Y_VIEW,
		POSITIVE_Z_VIEW,
		NEGATIVE_Z_VIEW
};

enum {	NOSELECTION=0,
		CTRLSELECTION,
		SHIFTSELECTION,
};

enum {	GEOMETRICTYPE=0,
};

enum {	CONSTANT_ATTENUATION=0,
		LINEAR_ATTENUATION,
		QUADRATIC_ATTENUATION
};

// Serialization types. Never delete an entry or change order!! (values are serialized!)
enum {	SINGLE_VIEW=0,
		FOUR_VIEWS,
		SIX_VIEWS_OLD,
		RESERVED_AND_PLACE_HOLDER1,
		HORIZONTALLY_DIVIDED,
		VERTICALLY_DIVIDED,
		HORIZONTALLY_DIVIDED_3,
		VERTICALLY_DIVIDED_3,
		HORIZONTAL_1_PLUS_3_VIEWS,
		VERTICAL_1_PLUS_3_VIEWS,
		HORIZONTAL_1_PLUS_4_VIEWS,
		VERTICAL_1_PLUS_4_VIEWS,
		SIX_VIEWS,
		EIGHT_VIEWS,
		CLOSING_VIEW_ITEM
};

#define BUTTON_MIN_X_SIZE 2			// In pixels
#define BUTTON_MIN_Y_SIZE 2			// In pixels
#define BUTTON_SLIDER_X_SIZE 0.2f	// Percentage of button x-size
#define BUTTON_SLIDER_Y_SIZE 0.8f	// Percentage of button y-size
#define MAX_X_BUTTONS 256			// Maximum number of buttons in a block (x)
#define MAX_Y_BUTTONS 256			// Maximum number of buttons in a block (y)

#define V_REP_SYSTEM_DIRECTORY_NAME "system" // "system\\"
#define V_REP_SCENES_DIRECTORY_NAME "scenes" // "scenes\\"
#define V_REP_MODELS_DIRECTORY_NAME "models" // "models\\"
#define V_REP_CADFILES_DIRECTORY_NAME "cadFiles" // "cadFiles\\"

// General serialization tags. Never change an entry!! (values are serialized!)
#define SER_SHAPE						"SHP"
#define SER_JOINT						"JNT"
#define SER_CAMERA						"CMA"
#define SER_LIGHT						"LGT"
#define SER_MIRROR						"MIR"
#define SER_DUMMY						"DMY"
#define SER_GRAPH						"GRH"
#define SER_PROXIMITYSENSOR				"SNR"
#define SER_VISIONSENSOR				"RSN"
#define SER_VERSATILE_OLD				"VRE"
//#define SER_GEOMETRIC_OLD				"GEO" // RESERVED TAG
#define SER_TEXTURE						"TEX"
#define SER_DYNMATERIAL					"DMA"
#define SER_ORDER_OLD_FORWARD_COMPATIBILITY_2010_07_14	"ORD" // Needed so that old V-REP versions can read newer V-REP files
#define SER_GROUP						"GRP"
#define SER_ENVIRONMENT					"ENV"
#define SER_GHOSTS						"GHO"
#define SER_FORWARD_COMPATIBILITY		"BCK"
#define SER_IK							"IKO"
#define SER_VIEWS						"VEW"
#define SER_COLLISION					"COL"
#define SER_DISTANCE					"DST"
#define SER_PATH						"PAT"
#define SER_VOLUME						"VOL"
#define SER_MILL						"MIL"
#define SER_FORCESENSOR					"FSE"
#define SER_PATH_PLANNING				"PPL"
#define SER_MOTION_PLANNING				"MPL"
#define SER_SETTINGS					"SET"
#define SER_DYNAMICS					"DYN"
#define SER_BUTTON_BLOCK				"BBK"
#define SER_LUA_SCRIPT					"LST"
#define SER_SCENE_CUSTOM_DATA			"CDS"
#define SER_OBJECT_CUSTOM_DATA			"CDO"
#define SER_GEOMETRIC_CONSTRAINT_OBJECT "GCO"
#define SER_SIMULATION					"SIM"
#define SER_MODEL_ACKNOWLEDGEMENTOLD_20100714		"MAC"
#define SER_MODEL_THUMBNAIL_OLD_COMPATIBILITY_2012_03_06				"MTB" // for backward compatibility
#define SER_MODEL_THUMBNAIL				"MTC"

// View selection modes:
enum {	NO_VIEW_SELECT_MODE=0,
		CAMERA_VIEW_SELECT_MODE,
		GRAPH_VIEW_SELECT_MODE,
		VISIONSENSOR_VIEW_SELECT_MODE,
		VIEWABLE_VIEW_SELECT_MODE
};

enum {
	NO_EDIT_MODE=0,
	TRIANGLE_EDIT_MODE=1,
	VERTEX_EDIT_MODE=2,
	EDGE_EDIT_MODE=4,
	SHAPE_EDIT_MODE=TRIANGLE_EDIT_MODE|VERTEX_EDIT_MODE|EDGE_EDIT_MODE,
	PATH_EDIT_MODE=8,
	SHAPE_OR_PATH_EDIT_MODE=SHAPE_EDIT_MODE|PATH_EDIT_MODE, // Edit mode when regular objects can't be selected
	BUTTON_EDIT_MODE=16
};

// Group types:
enum {	GROUP_LOOSE=0,
		GROUP_FROM_BASE_INCLUDED,
		GROUP_FROM_BASE_EXCLUDED,
		GROUP_FROM_TIP_INCLUDED,
		GROUP_FROM_TIP_EXCLUDED,
		GROUP_EVERYTHING
};




// Graphing objects. Never remove an element!! (instead replace it with an dummy name
// (RESERVED0)). These values are serialized!
// When changing something here, don't forget to change the 
// performeObjectLoadingMapping-
// performGroupLoadingMapping-
// performCollisionLoadingMapping-
// ...
// announceObjectWillBeErased-
// announceGroupWillBeErased-
// announceCollisionWillBeErased-
// ...
// routines in CGraphData!!!!!
// and the getCyclicAndRange function in graph!!!!!!!!!!!!
// and the adjustDataToUserMetric function graph!!!!!!!!
enum {
	GRAPH_3DOBJECT_START=0,			// From here, streams associated with a 3DObject ID:
	GRAPH_3DOBJECT_ALL_X_ABS,
	GRAPH_3DOBJECT_ALL_Y_ABS,
	GRAPH_3DOBJECT_ALL_Z_ABS,
	GRAPH_3DOBJECT_ALL_X_REL,
	GRAPH_3DOBJECT_ALL_Y_REL,
	GRAPH_3DOBJECT_ALL_Z_REL,
	GRAPH_3DOBJECT_ALL_ALPHA_ABS,
	GRAPH_3DOBJECT_ALL_BETA_ABS,
	GRAPH_3DOBJECT_ALL_GAMMA_ABS,
	GRAPH_3DOBJECT_ALL_ALPHA_REL,
	GRAPH_3DOBJECT_ALL_BETA_REL,
	GRAPH_3DOBJECT_ALL_GAMMA_REL,

	GRAPH_3DOBJECT_ALL_XVEL_ABS,
	GRAPH_3DOBJECT_ALL_YVEL_ABS,
	GRAPH_3DOBJECT_ALL_ZVEL_ABS,
	GRAPH_3DOBJECT_ALL_VEL_ABS,
	GRAPH_3DOBJECT_ALL_ANGULAR_VEL_ABS,


	GRAPH_3DOBJECT_PROXSENSOR_SUBSTART=500,			// sub-start
	GRAPH_3DOBJECT_PROXSENSOR_X_ABS,
	GRAPH_3DOBJECT_PROXSENSOR_Y_ABS,
	GRAPH_3DOBJECT_PROXSENSOR_Z_ABS,
	GRAPH_3DOBJECT_PROXSENSOR_X_REL,
	GRAPH_3DOBJECT_PROXSENSOR_Y_REL,
	GRAPH_3DOBJECT_PROXSENSOR_Z_REL,
	GRAPH_3DOBJECT_PROXSENSOR_X_REL_TO_SENSOR,
	GRAPH_3DOBJECT_PROXSENSOR_Y_REL_TO_SENSOR,
	GRAPH_3DOBJECT_PROXSENSOR_Z_REL_TO_SENSOR,
	GRAPH_3DOBJECT_PROXSENSOR_DIST,
	GRAPH_3DOBJECT_PROXSENSOR_AZIMUTH,
	GRAPH_3DOBJECT_PROXSENSOR_ELEVATION,
	GRAPH_3DOBJECT_PROXSENSOR_DETECTION_STATE,
	GRAPH_3DOBJECT_PROXSENSOR_CALCULATION_TIME,
	GRAPH_3DOBJECT_PROXSENSOR_SUBEND=550,				// sub-end
	GRAPH_3DOBJECT_VISIONSENSOR_SUBSTART=551,		// sub-start
	GRAPH_3DOBJECT_VISIONSENSOR_MIN_RED,
	GRAPH_3DOBJECT_VISIONSENSOR_MAX_RED,
	GRAPH_3DOBJECT_VISIONSENSOR_AVG_RED,
	GRAPH_3DOBJECT_VISIONSENSOR_MIN_GREEN,
	GRAPH_3DOBJECT_VISIONSENSOR_MAX_GREEN,
	GRAPH_3DOBJECT_VISIONSENSOR_AVG_GREEN,
	GRAPH_3DOBJECT_VISIONSENSOR_MIN_BLUE,
	GRAPH_3DOBJECT_VISIONSENSOR_MAX_BLUE,
	GRAPH_3DOBJECT_VISIONSENSOR_AVG_BLUE,
	GRAPH_3DOBJECT_VISIONSENSOR_MIN_INTENSITY,
	GRAPH_3DOBJECT_VISIONSENSOR_MAX_INTENSITY,
	GRAPH_3DOBJECT_VISIONSENSOR_AVG_INTENSITY,
	GRAPH_3DOBJECT_VISIONSENSOR_MIN_DEPTH,
	GRAPH_3DOBJECT_VISIONSENSOR_MAX_DEPTH,
	GRAPH_3DOBJECT_VISIONSENSOR_AVG_DEPTH,
	GRAPH_3DOBJECT_VISIONSENSOR_DETECTION_STATE,
	GRAPH_3DOBJECT_VISIONSENSOR_CALCULATION_TIME,
	GRAPH_3DOBJECT_VISIONSENSOR_SUBEND=650,				// sub-end
	GRAPH_3DOBJECT_JOINT_SUBSTART=651,					// sub-start
	GRAPH_3DOBJECT_JOINT_POSITION,
	GRAPH_3DOBJECT_JOINT_DYN_POSITION_ERROR,
	GRAPH_3DOBJECT_JOINT_DYN_ORIENTATION_ERROR,
	GRAPH_3DOBJECT_JOINT_DYN_FORCE_OR_TORQUE,
	GRAPH_3DOBJECT_JOINT_VELOCITY,
	GRAPH_3DOBJECT_JOINT_SUBEND=700,				// sub-end

	GRAPH_3DOBJECT_PATH_SUBSTART=701,					// sub-start
	GRAPH_3DOBJECT_PATH_POSITION,
	GRAPH_3DOBJECT_PATH_POSITION_LINEAR_COMPONENT,
	GRAPH_3DOBJECT_PATH_POSITION_ANGULAR_COMPONENT,
	GRAPH_3DOBJECT_PATH_SUBEND=750,				// sub-end

	GRAPH_3DOBJECT_MILL_SUBSTART=751,			// sub-start
	GRAPH_3DOBJECT_MILL_CUT_SURFACE,
	GRAPH_3DOBJECT_MILL_CUT_VOLUME,
	GRAPH_3DOBJECT_MILL_CALCULATION_TIME,
	GRAPH_3DOBJECT_MILL_SUBEND=770,				// sub-end

	GRAPH_3DOBJECT_FORCESENSOR_SUBSTART=771,			// sub-start
	GRAPH_3DOBJECT_FORCESENSOR_FORCE_X,
	GRAPH_3DOBJECT_FORCESENSOR_FORCE_Y,
	GRAPH_3DOBJECT_FORCESENSOR_FORCE_Z,
	GRAPH_3DOBJECT_FORCESENSOR_FORCE_LENGTH,
	GRAPH_3DOBJECT_FORCESENSOR_TORQUE_X,
	GRAPH_3DOBJECT_FORCESENSOR_TORQUE_Y,
	GRAPH_3DOBJECT_FORCESENSOR_TORQUE_Z,
	GRAPH_3DOBJECT_FORCESENSOR_TORQUE_LENGTH,
	GRAPH_3DOBJECT_FORCESENSOR_POSITION_ERROR,
	GRAPH_3DOBJECT_FORCESENSOR_ORIENTATION_ERROR,
	GRAPH_3DOBJECT_FORCESENSOR_BROKEN,
	GRAPH_3DOBJECT_FORCESENSOR_SUBEND=790,				// sub-end


	GRAPH_3DOBJECT_END=2000,					//End
	GRAPH_COLLISION_START=2001,					//Start
	GRAPH_COLLISION_BOOLEAN,
	GRAPH_COLLISION_CALCULATION_TIME,
	GRAPH_COLLISION_END=2100,					//End
	GRAPH_DISTANCE_START=2101,					//Start
	GRAPH_DISTANCE_DIST,
	GRAPH_DISTANCE_SEG1_X_ABS,
	GRAPH_DISTANCE_SEG1_Y_ABS,
	GRAPH_DISTANCE_SEG1_Z_ABS,
	GRAPH_DISTANCE_SEG2_X_ABS,
	GRAPH_DISTANCE_SEG2_Y_ABS,
	GRAPH_DISTANCE_SEG2_Z_ABS,
	GRAPH_DISTANCE_SEG1_X_REL,
	GRAPH_DISTANCE_SEG1_Y_REL,
	GRAPH_DISTANCE_SEG1_Z_REL,
	GRAPH_DISTANCE_SEG2_X_REL,
	GRAPH_DISTANCE_SEG2_Y_REL,
	GRAPH_DISTANCE_SEG2_Z_REL,
	GRAPH_DISTANCE_CALCULATION_TIME,
	GRAPH_DISTANCE_END=2400,					//End
	GRAPH_IK_START=2401,						//Start
	GRAPH_IK_CALCULATION_TIME,
	GRAPH_IK_END=2500,							//End
	GRAPH_GCS_START=2501,						//Start
	GRAPH_GCS_CALCULATION_TIME,
	GRAPH_GCS_END=2600,							//End
	GRAPH_NOOBJECT_START=2601,					//Start
	GRAPH_NOOBJECT_TIME,
	GRAPH_NOOBJECT_COLLISION_QUANTITY,
	GRAPH_NOOBJECT_PROXSENSOR_OVERALL_CALCULATION_TIME,
	GRAPH_NOOBJECT_COLLISION_OVERALL_CALCULATION_TIME,
	GRAPH_NOOBJECT_DISTANCE_OVERALL_CALCULATION_TIME,
	GRAPH_NOOBJECT_VISIONSENSOR_OVERALL_CALCULATION_TIME,
	GRAPH_NOOBJECT_IK_OVERALL_CALCULATION_TIME,
	GRAPH_NOOBJECT_GCS_OVERALL_CALCULATION_TIME,
	GRAPH_NOOBJECT_MAINSCRIPT_EXECUTION_TIME,
	GRAPH_NOOBJECT_USER_DEFINED,
	GRAPH_NOOBJECT_MILL_OVERALL_CALCULATION_TIME,
	GRAPH_NOOBJECT_MILL_OVERALL_CUT_SURFACE,
	GRAPH_NOOBJECT_MILL_OVERALL_CUT_VOLUME,
	GRAPH_NOOBJECT_DYNAMICS_OVERALL_CALCULATION_TIME,
	GRAPH_NOOBJECT_SIMULATIONPASS_EXECUTION_TIME,
	GRAPH_NOOBJECT_RENDERING_TIME,
	GRAPH_NOOBJECT_WORK_THREADS_EXECUTION_TIME,
	GRAPH_NOOBJECT_END=3000,					//End

};



#define SELECTION_BUFFER_SIZE 100000	// Specifies how many objects can be selected at the (from 10000 to 100000 on 14/6/2011)
										// same time with the shift selection


// Hierarchy and other pictures (TGA format):
enum {NO_TREE_PICTURE=0,
	SIMPLE_SHAPE_TREE_PICTURE,
	MULTI_SHAPE_TREE_PICTURE,
	PURE_SHAPE_TREE_PICTURE,
	HEIGHTFIELD_SHAPE_TREE_PICTURE,
	PURE_MULTISHAPE_TREE_PICTURE,
	REVOLUTE_JOINT_TREE_PICTURE,
	PRISMATIC_JOINT_TREE_PICTURE,
	SPHERICAL_JOINT_TREE_PICTURE,
	CAMERA_TREE_PICTURE,
	MIRROR_TREE_PICTURE,
	CONVEX_SHAPE_TREE_PICTURE,
	CONVEX_MULTISHAPE_TREE_PICTURE,
	CLIPPLANE_TREE_PICTURE,
	OMNI_LIGHT_ON_TREE_PICTURE,
	OMNI_LIGHT_OFF_TREE_PICTURE,
	SPOT_LIGHT_ON_TREE_PICTURE,
	SPOT_LIGHT_OFF_TREE_PICTURE,
	DIR_LIGHT_ON_TREE_PICTURE,
	DIR_LIGHT_OFF_TREE_PICTURE,
	GRAPH_TREE_PICTURE,
	DUMMY_TREE_PICTURE,
	MODEL_TREE_PICTURE,
	PROXIMITYSENSOR_TREE_PICTURE,
	VISIONSENSOR_TREE_PICTURE,
	PATH_TREE_PICTURE,
	MILL_TREE_PICTURE,
	WORLD_TREE_PICTURE,
	FORCE_SENSOR_TREE_PICTURE,
	WARNING_PICTURE,
	DYNAMICS_PICTURE,
	FOLDER_PICTURE,
	MINUS_SIGN_TREE_PICTURE,
	PLUS_SIGN_TREE_PICTURE,
	MAIN_SCRIPT_PICTURE,
	MAIN_SCRIPT_CUSTOMIZED_PICTURE,
	SCRIPT_PICTURE,
	CHECKED_BACKGROUND_PICTURE,
	SCRIPT_THREADED_PICTURE,
	SCRIPT_PARAMETERS_PICTURE,
	SCRIPT_PARAMETERS_ACTIVE_PICTURE,
	PATH_POINT_PICTURE,
	VERTEX_PICTURE,
	TRIANGLE_PICTURE,
	EDGE_PICTURE,
	BUTTON_BLOCK_PICTURE,
	CURSOR_ARROW,
	CURSOR_FINGER,
	CURSOR_ALL_DIR,
	CURSOR_HORIZONTAL_DIR,
	CURSOR_VERTICAL_DIR,
	CURSOR_SLASH_DIR,
	CURSOR_BACKSLASH_DIR,
	CURSOR_NO_BUTTON,
	CURSOR_LEFT_BUTTON,
	CURSOR_MIDDLE_BUTTON,
	CURSOR_RIGHT_BUTTON,
	EDU_TAG,
	VREP_TAG,
	EVAL_TAG,
	CURSOR_WHEEL_BUTTON,
	CURSOR_SHIFT_BUTTON,
	CURSOR_CTRL_BUTTON,
};

#define BROWSER_HIERARCHY_TITLE_BAR_HEIGHT 16
#define BROWSER_HIERARCHY_TITLE_BAR_CLOSING_BUTTON_WIDTH 16
#define BROWSER_HIERARCHY_MAIN_RENDERING_WINDOW_SEPARATION_WIDTH 2
#define HIERARCHY_SCROLLBAR_WIDTH (BROWSER_HIERARCHY_TITLE_BAR_CLOSING_BUTTON_WIDTH+2)


#define MAX_NUMBER_OF_PAGES 128 // Don't change (serialization problems!)

#define NON_OBJECT_PICKING_ID_BANNER_START SIM_IDSTART_COLLECTION
#define NON_OBJECT_PICKING_ID_BANNER_END (NON_OBJECT_PICKING_ID_BANNER_START+10000)
#define NON_OBJECT_PICKING_ID_PATH_PTS_START (NON_OBJECT_PICKING_ID_BANNER_END+1)

// Special keys and commands:
// (esc-key is handled in the windows messaging part and sends a "looseFocus" command
enum {	TAB_KEY=2000,
		ENTER_KEY,
		BACKSPACE_KEY,
		DELETE_KEY,
		CTRL_X_KEY,
		CTRL_C_KEY,
		CTRL_V_KEY,
		UP_KEY,
		DOWN_KEY,
		LEFT_KEY,
		RIGHT_KEY,
		ESC_KEY,
		CTRL_Y_KEY,
		CTRL_Z_KEY,
		CTRL_S_KEY,
		CTRL_O_KEY,
		CTRL_A_KEY,
		CTRL_W_KEY,
		CTRL_Q_KEY,
		CTRL_N_KEY,
		CTRL_SPACE_KEY,
		CTRL_D_KEY,
		CTRL_G_KEY,
		CTRL_E_KEY,
};

// Rich text items
enum {
	COLOR_AND_COLOR_RESET_RICH_TEXT=0,
	BOX_RICH_TEXT,
	PAUSE_RICH_TEXT,
	START_RICH_TEXT,
	END_RICH_TEXT,
	ARROW_LEFT_RICH_TEXT,
	ARROW_RIGHT_RICH_TEXT,
	ARROW_UP_RICH_TEXT,
	ARROW_DOWN_RICH_TEXT,
	CHECK_RICH_TEXT,
	SQUARE_RICH_TEXT,
	MINIMIZE_RICH_TEXT
};

// menu items
enum {	NO_COMMAND_CMD=1, // Always start at 1!!!!
		
		OBJECT_FULL_COPY_CMD,
		PASTE_OBJECTS_CMD,
		EMPTY_OBJECT_COPY_BUFFER_CMD,
		DELETE_OBJECTS_CMD,
		OBJECT_FULL_CUT_CMD,
		SELECT_ALL_OBJECTS_CMD,
		SELECT_ALL_SHAPE_EDIT_MODE_ITEMS_CMD,
		SELECT_ALL_PATH_POINTS_CMD,

		EMPTY_PATH_CMD,
		ROLL_PATH_POINTS_FORWARD_CMD,
		ROLL_PATH_POINTS_BACKWARD_CMD,

		ENTER_SHAPE_EDIT_MODE_CMD,

		ENTER_PATH_EDIT_MODE_CMD,
		ALIGN_BOUNDING_BOX_WITH_MAIN_AXIS_CMD,
		ALIGN_BOUNDING_BOX_WITH_WORLD_CMD,
		ALIGN_BOUNDING_BOX_WITH_TUBE_MAIN_AXIS_CMD,
		ALIGN_BOUNDING_BOX_WITH_CUBOID_MAIN_AXIS_CMD,

		LEAVE_EDIT_MODE_CANCEL_CHANGES_CMD,
		LEAVE_EDIT_MODE_CMD,
		FLIP_TRIANGLES_SIDE_CMD,
		INSERT_TRIANGLES_CMD,
		INSERT_TRIANGLE_FAN_CMD,
		MAKE_SHAPE_WITH_SELECTED_TRIANGLES_CMD,
		MAKE_RECTANGLE_WITH_SELECTED_TRIANGLES_CMD,
		MAKE_SPHERE_WITH_SELECTED_TRIANGLES_CMD,
		MAKE_SPHEROID_WITH_SELECTED_TRIANGLES_CMD,
		MAKE_CYLINDER_WITH_SELECTED_TRIANGLES_CMD,
		MAKE_DUMMIES_WITH_SELECTED_VERTICES_CMD,
		MAKE_PATH_WITH_SELECTED_EDGES_CMD,
		MAKE_SELECTED_EDGES_INVISIBLE_CMD,
		MAKE_SELECTED_EDGES_VISIBLE_CMD,
		SWAP_TO_VERTEX_EDIT_MODE_CMD,
		SWAP_TO_TRIANGLE_EDIT_MODE_CMD,
		SWAP_TO_EDGE_EDIT_MODE_CMD,
		TRIANGLE_VERTEX_COPY_CMD,
		PASTE_TRIANGLE_VERTEX_CMD,
		EMPTY_TRIANGLE_VERTEX_COPY_BUFFER_CMD,
		DELETE_TRIANGLE_VERTEX_EDGE_CMD,
		TRIANGLE_VERTEX_CUT_CMD,
		TOGGLE_EDIT_MODE_HIDDEN_VERTICE_EDGE_SHOW_CMD,
		TOGGLE_EDIT_MODE_AUTOMATIC_EDGE_FOLLOWING_CMD,
		DIVIDE_LARGEST_TRIANGLES_CMD,

		PATH_POINT_COPY_CMD,
		PASTE_PATH_POINT_CMD,
		DELETE_PATH_POINT_CMD,
		PATH_POINT_CUT_CMD,
		INSERT_NEW_PATH_POINT_CMD,
		APPEND_NEW_PATH_POINT_FROM_CAMERA_CMD,
		MAKE_PATH_FROM_BEZIER_PATH_CMD,
		KEEP_ALL_X_AND_ALIGN_Z_FOR_PATH_POINTS_CMD,

		MAKE_PARENT_CMD,
		MAKE_ORPHANS_CMD,
		REPLACE_OBJECTS_CMD,
		MORPH_INTO_CONVEX_CMD,

		UNLINK_DUMMIES_CMD,
		LINK_DUMMIES_DYNAMICS_LOOP_CLOSURE,
		LINK_DUMMIES_DYNAMICS_FORCE_CONSTRAINT,
		LINK_DUMMIES_GCS_LOOP_CLOSURE,
		LINK_DUMMIES_GCS_TIP,
		LINK_DUMMIES_GCS_TARGET,
		LINK_DUMMIES_IK_TIP_TARGET,

		CREATE_SINGLE_VIEW_TYPE_CMD,
		CREATE_FOUR_VIEW_TYPE_CMD,
		CREATE_SIX_VIEW_TYPE_CMD,
		CREATE_EIGHT_VIEW_TYPE_CMD,
		CREATE_HORIZONTAL_VIEW_TYPE_CMD,
		CREATE_VERTICAL_VIEW_TYPE_CMD,
		CREATE_HORIZONTAL_3_VIEW_TYPE_CMD,
		CREATE_VERTICAL_3_VIEW_TYPE_CMD,
		CREATE_HORIZONTAL_1_PLUS_3_VIEW_TYPE_CMD,
		CREATE_VERTICAL_1_PLUS_3_VIEW_TYPE_CMD,
		CREATE_HORIZONTAL_1_PLUS_4_VIEW_TYPE_CMD,
		CREATE_VERTICAL_1_PLUS_4_VIEW_TYPE_CMD,

		TOGGLE_SOLID_DISPLAY_CMD,
		SOLID_DISPLAY_CMD,
		WIREFRAME_EDGES_DISPLAY_CMD,
		WIREFRAME_TRIANGLES_DISPLAY_CMD,
		BOUNDINGBOX_SOLID_DISPLAY_CMD,
		BOUNDINGBOX_WIREFRAME_DISPLAY_CMD,
		TEXTURED_DISPLAY_CMD,
		SHOW_INERTIAS_CMD,
		PERSPECTIVE_DISPLAY_CMD,

		VIEW_FIT_TO_SCENE_CMD,
		VIEW_FIT_TO_SELECTION_CMD,

		SHOW_EDGES_CMD,
		THICK_EDGES_CMD,
		XY_GRAPH_DISPLAY_CMD,
		XY_GRAPH_AUTO_MODE_DURING_SIMULATION_CMD,
		TIME_GRAPH_X_AUTO_MODE_DURING_SIMULATION_CMD,
		TIME_GRAPH_Y_AUTO_MODE_DURING_SIMULATION_CMD,
		XY_GRAPH_KEEP_PROPORTIONS_AT_ONE_ONE_CMD,
		MAKE_GRAPH_CURVE_STATIC_CMD,
		COPY_GRAPH_CURVE_TO_CLIPBOARD_CMD,

		LOOK_THROUGH_CAMERA_CMD,
		LOOK_AT_GRAPH_CMD,
		LOOK_AT_VISION_SENSOR_CMD,
		TRACK_OBJECT_CMD,
		DONT_TRACK_OBJECT_CMD,

		REMOVE_VIEW_CMD,
		PAGE_SELECTOR_CMD,
		SCENE_SELECTOR_CMD,
		ADD_FLOATING_VIEW_CMD,

		VIEW_SELECTOR_CAMERA_CMD,
		VIEW_SELECTOR_GRAPH_CMD,
		VIEW_SELECTOR_VISION_SENSOR_CMD,
		VIEW_SELECTOR_ANY_CMD,

		START_RESUME_SIMULATION_REQUEST_CMD, // Coming from a toolbar click or menu selection
		PAUSE_SIMULATION_REQUEST_CMD,
		STOP_SIMULATION_REQUEST_CMD,

		TOGGLE_TO_BULLET_ENGINE_CMD,
		TOGGLE_TO_ODE_ENGINE_CMD,
		TOGGLE_TO_VORTEX_ENGINE_CMD,

		OPEN_GRAPH_DLG_CMD,
		OPEN_CAMERA_DLG_CMD,
		OPEN_LIGHT_DLG_CMD,
		OPEN_MIRROR_DLG_CMD,
		OPEN_SHAPE_DLG_CMD,
		OPEN_PROXIMITY_SENSOR_DLG_CMD,
		OPEN_VISION_SENSOR_DLG_CMD,
		OPEN_MILL_DLG_CMD,

		OPEN_SHAPE_EDITION_DLG_CMD,
		OPEN_OBJECT_DLG_CMD,
		OPEN_OBJECT_DLG_OBJECT_SPECIFIC_PART_CMD,
		OPEN_CALCULATION_DLG_CMD,

		OPEN_FORCE_SENSOR_DLG_CMD,
		OPEN_DUMMY_DLG_CMD,
		OPEN_JOINT_DLG_CMD,
		OPEN_PATH_DLG_CMD,
		OPEN_BUTTON_DLG_CMD,
		OPEN_TRANSFORMATIONS_DLG_CMD,
		OPEN_ENVIRONMENT_DLG_CMD,
		OPEN_FOG_DLG_CMD,

		TOGGLE_GENERAL_PROPERTIES_DLG_CMD,
		TOGGLE_GRAPH_DLG_CMD,
		TOGGLE_TRANSFORMATIONS_DLG_CMD,
		TOGGLE_COLLECTION_DLG_CMD,
		TOGGLE_CAMERA_DLG_CMD,
		TOGGLE_LIGHT_DLG_CMD,
		TOGGLE_MIRROR_DLG_CMD,
		TOGGLE_COLLISION_DLG_CMD,
		TOGGLE_SELECTION_DLG_CMD,
		TOGGLE_SHAPE_DLG_CMD,
		TOGGLE_PROXIMITY_SENSOR_DLG_CMD,
		TOGGLE_VISION_SENSOR_DLG_CMD,
		TOGGLE_MILL_DLG_CMD,
		TOGGLE_FORCE_SENSOR_DLG_CMD,
		TOGGLE_LUA_SCRIPT_DLG_CMD,
		TOGGLE_SETTINGS_DLG_CMD,
		TOGGLE_DUMMY_DLG_CMD,
		TOGGLE_DISTANCE_DLG_CMD,
		TOGGLE_JOINT_DLG_CMD,
		TOGGLE_ENVIRONMENT_DLG_CMD,
		TOGGLE_IK_DLG_CMD,
		TOGGLE_BUTTON_DLG_CMD,
		TOGGLE_CUSTOM_UI_DLG_CMD,
		TOGGLE_SHAPE_EDITION_DLG_CMD,
		TOGGLE_PATH_EDITION_DLG_CMD,
		TOGGLE_HIERARCHY_DLG_CMD,
		TOGGLE_BROWSER_DLG_CMD,
		TOGGLE_LAYERS_DLG_CMD,
		TOGGLE_DYNAMICS_DLG_CMD,
		TOGGLE_PATH_DLG_CMD,
		TOGGLE_OBJECT_DLG_CMD,
		TOGGLE_CALCULATION_DLG_CMD,
		TOGGLE_PATH_PLANNING_DLG_CMD,
		TOGGLE_CONSTRAINT_SOLVER_DLG_CMD,
		TOGGLE_SIMULATION_DLG_CMD,
		TOGGLE_AVI_RECORDER_DLG_CMD,

		CLOSE_SCENE_CMD,
		NEW_SCENE_CMD,
		OPEN_SCENE_CMD,
		OPEN_RECENT_SCENE0_CMD,
		OPEN_RECENT_SCENE1_CMD,
		OPEN_RECENT_SCENE2_CMD,
		OPEN_RECENT_SCENE3_CMD,
		OPEN_RECENT_SCENE4_CMD,
		OPEN_RECENT_SCENE5_CMD,
		OPEN_RECENT_SCENE6_CMD,
		OPEN_RECENT_SCENE7_CMD,
		OPEN_RECENT_SCENE8_CMD,
		OPEN_RECENT_SCENE9_CMD,
		LOAD_MODEL_CMD,
		LOAD_UI_CMD,
		SAVE_SCENE_CMD,
		SAVE_SCENE_AS_CMD,
		EXPORT_IK_CONTENT_CMD,
		SAVE_MODEL_CMD,
		SAVE_UI_CMD,
		IMPORT_MESH_CMD,
		IMPORT_PATH_CMD,
		IMPORT_HEIGHTFIELD_CMD,

		EXPORT_SHAPE_CMD,
		EXPORT_GRAPHS_CMD,
		EXPORT_PATH_SIMPLE_POINTS_CMD,
		EXPORT_PATH_BEZIER_POINTS_CMD,
		EXPORT_DYNAMIC_CONTENT_CMD,
		EXIT_SIMULATOR_CMD,

		CAMERA_SHIFT_TO_FRAME_SELECTION_CMD,
		CAMERA_SHIFT_NAVIGATION_CMD,
		CAMERA_ROTATE_NAVIGATION_CMD,
		CAMERA_ZOOM_NAVIGATION_CMD,
		CAMERA_TILT_NAVIGATION_CMD,
		CAMERA_ANGLE_NAVIGATION_CMD,
		CAMERA_FLY_NAVIGATION_CMD,
		OBJECT_SHIFT_NAVIGATION_CMD,
		OBJECT_ROTATE_NAVIGATION_CMD,
		OBJECT_SELECTION_SELECTION_CMD,
		CLEAR_SELECTION_SELECTION_CMD,
		PATH_POINT_CREATION_MODE_CMD,

		VIEW_1_CMD,
		VIEW_2_CMD,
		VIEW_3_CMD,
		VIEW_4_CMD,
		VIEW_5_CMD,
		VIEW_6_CMD,
		VIEW_7_CMD,
		VIEW_8_CMD,

		SWITCH_TO_INSTANCE_INDEX0_CMD,
		SWITCH_TO_INSTANCE_INDEX1_CMD,
		SWITCH_TO_INSTANCE_INDEX2_CMD,
		SWITCH_TO_INSTANCE_INDEX3_CMD,
		SWITCH_TO_INSTANCE_INDEX4_CMD,
		SWITCH_TO_INSTANCE_INDEX5_CMD,
		SWITCH_TO_INSTANCE_INDEX6_CMD,
		SWITCH_TO_INSTANCE_INDEX7_CMD,
		SWITCH_TO_INSTANCE_INDEX8_CMD,
		SWITCH_TO_INSTANCE_INDEX9_CMD,
		SWITCH_TO_INSTANCE_INDEX10_CMD,
		SWITCH_TO_INSTANCE_INDEX11_CMD,
		SWITCH_TO_INSTANCE_INDEX12_CMD,
		SWITCH_TO_INSTANCE_INDEX13_CMD,
		SWITCH_TO_INSTANCE_INDEX14_CMD,
		SWITCH_TO_INSTANCE_INDEX15_CMD,
		SWITCH_TO_INSTANCE_INDEX16_CMD,
		SWITCH_TO_INSTANCE_INDEX17_CMD,
		SWITCH_TO_INSTANCE_INDEX18_CMD,
		SWITCH_TO_INSTANCE_INDEX19_CMD,
		SWITCH_TO_INSTANCE_INDEX20_CMD,
		SWITCH_TO_INSTANCE_INDEX21_CMD,
		SWITCH_TO_INSTANCE_INDEX22_CMD,
		SWITCH_TO_INSTANCE_INDEX23_CMD,
		SWITCH_TO_INSTANCE_INDEX24_CMD,
		SWITCH_TO_INSTANCE_INDEX25_CMD,
		SWITCH_TO_INSTANCE_INDEX26_CMD,
		SWITCH_TO_INSTANCE_INDEX27_CMD,
		SWITCH_TO_INSTANCE_INDEX28_CMD,
		SWITCH_TO_INSTANCE_INDEX29_CMD,
		SWITCH_TO_INSTANCE_INDEX30_CMD,
		SWITCH_TO_INSTANCE_INDEX31_CMD,
		SWITCH_TO_INSTANCE_INDEX32_CMD,
		SWITCH_TO_INSTANCE_INDEX33_CMD,
		SWITCH_TO_INSTANCE_INDEX34_CMD,
		SWITCH_TO_INSTANCE_INDEX35_CMD,
		SWITCH_TO_INSTANCE_INDEX36_CMD,
		SWITCH_TO_INSTANCE_INDEX37_CMD,
		SWITCH_TO_INSTANCE_INDEX38_CMD,
		SWITCH_TO_INSTANCE_INDEX39_CMD,

		ADD_CAMERA_CMD,
		ADD_OMNI_LIGHT_CMD,
		ADD_SPOT_LIGHT_CMD,
		ADD_DIR_LIGHT_CMD,
		ADD_REVOLUTE_JOINT_CMD,
		ADD_PRISMATIC_JOINT_CMD,
		ADD_SPHERICAL_JOINT_CMD,
		ADD_DUMMY_CMD,
		ADD_MIRROR_CMD,
		ADD_GRAPH_CMD,
		ADD_RAY_PROXSENSOR_CMD,
		ADD_PYRAMID_PROXSENSOR_CMD,
		ADD_CYLINDER_PROXSENSOR_CMD,
		ADD_DISC_PROXSENSOR_CMD,
		ADD_CONE_PROXSENSOR_CMD,
		ADD_RANDOMIZED_RAY_PROXSENSOR_CMD,

		ADD_PYRAMID_MILL_CMD,
		ADD_CYLINDER_MILL_CMD,
		ADD_DISC_MILL_CMD,
		ADD_CONE_MILL_CMD,


		ADD_ORTHOGONAL_VISION_SENSOR_CMD,
		ADD_PERSPECTIVE_VISION_SENSOR_CMD,
		ADD_FORCE_SENSOR_CMD,
		ADD_PATH_SEGMENT_CMD,
		ADD_PATH_CIRCLE_CMD,

		ADD_AND_ASSOCIATE_NON_THREADED_CHILD_SCRIPT_CMD,
		ADD_AND_ASSOCIATE_THREADED_CHILD_SCRIPT_CMD,

		ADD_CONVEX_HULL_CMD,
		ADD_CONVEX_DECOMPOSITION_CMD,

		ADD_PRIMITIVE_PLANE_CMD,
		ADD_PRIMITIVE_DISC_CMD,
		ADD_PRIMITIVE_RECTANGLE_CMD,
		ADD_PRIMITIVE_SPHERE_CMD,
		ADD_PRIMITIVE_CYLINDER_CMD,

		GROUP_SHAPES_CMD,
		UNGROUP_SHAPES_CMD,
		MERGE_SHAPES_CMD,
		DIVIDE_SHAPES_CMD,
		MERGE_PATHS_CMD,

		ADDITIONAL_TOOL_MENU_ITEM_START_CMD,
		ADDITIONAL_TOOL_MENU_ITEM_END_CMD=ADDITIONAL_TOOL_MENU_ITEM_START_CMD+100,

		EXPAND_HIERARCHY_CMD,
		COLLAPSE_HIERARCHY_CMD,
		EXPAND_SELECTED_HIERARCHY_CMD,
		COLLAPSE_SELECTED_HIERARCHY_CMD,

		HIERARCHY_COLORING_NONE_CMD,
		HIERARCHY_COLORING_RED_CMD,
		HIERARCHY_COLORING_GREEN_CMD,
		HIERARCHY_COLORING_BLUE_CMD,

		ENTER_BUTTON_EDIT_MODE_CMD,
		COPY_2DELEMENT_CMD,
		PASTE_2DELEMENT_CMD,
		DELETE_2DELEMENT_CMD,
		CUT_2DELEMENT_CMD,
		LEAVE_BUTTON_EDIT_MODE_CMD,

		HELP_TOPICS_CMD,
		ABOUT_CMD,
		CREDITS_CMD,
		ENTER_KEY_CMD,
		KEEP_ME_UPDATED_CMD,

		UNDO_CMD,
		REDO_CMD,
		ASSEMBLE_CMD,
		TRANSFER_DNA_CMD,
		TOGGLE_DYNAMIC_CONTENT_VISUALIZATION_CMD,
		TOGGLE_REAL_TIME_SIMULATION_CMD,
		SLOWER_SIMULATION_CMD,
		FASTER_SIMULATION_CMD,
		THREADED_RENDERING_CMD,
		ADDON_SCRIPT_MENU_ITEM_START_CMD,
		ADDON_SCRIPT_MENU_ITEM_END_CMD=ADDON_SCRIPT_MENU_ITEM_START_CMD+30,
		ADDON_FUNCTION_MENU_ITEM_START_CMD,
		ADDON_FUNCTION_MENU_ITEM_END_CMD=ADDON_FUNCTION_MENU_ITEM_START_CMD+30,

		SHOW_GUI_SIM_THREAD_SYNC_ACTIVITY_DEBUG_CMD,
		SHOW_GUI_SIM_THREAD_SYNC_FAILS_ACTIVITY_DEBUG_CMD,
		SHOW_INTERNAL_FUNCTION_ACCESS_DEBUG_CMD,
		SHOW_C_API_ACCESS_DEBUG_CMD,
		SHOW_LUA_API_ACCESS_DEBUG_CMD,
		SHOW_EASYLOCK_ACTIVITY_DEBUG_CMD,
		SHOW_THREAD_SWITCHES_DEBUG_CMD,
		DEBUG_TO_FILE_DEBUG_CMD,
		DISABLE_FRUSTUM_CULLING_DEBUG_CMD,
		DISABLE_COLLISION_CACHING_DEBUG_CMD,
		DISABLE_DISTANCE_CACHING_DEBUG_CMD,

		OUTSIDE_CUSTOMIZED_COMMANDS_START_CMD=10000
};



#define piValue 3.14159265359f
#define piValD2 1.570796326794f
#define piValTimes2 6.28318530718f
#define radToDeg 57.2957795130785499f
#define degToRad 0.017453292519944444f

#define IK_DIVISION_FACTOR 100.0f

enum { // VERY CAREFUL, FOLLOWING VALUES ARE SERIALIZED!!
		SIM_IDSTART_3DOBJECT			=0,
		SIM_IDSTART_COLLECTION_OLD		=100000,
		SIM_IDEND_3DOBJECT				=1999999,
		SIM_IDSTART_COLLECTION			=2000000,
		SIM_IDEND_COLLECTION			=SIM_IDSTART_COLLECTION+10000,
		SIM_IDSTART_COLLISION			=SIM_IDEND_COLLECTION+1,
		SIM_IDEND_COLLISION				=SIM_IDSTART_COLLISION+10000,
		SIM_IDSTART_DISTANCE			=SIM_IDEND_COLLISION+1,
		SIM_IDEND_DISTANCE				=SIM_IDSTART_DISTANCE+10000,
		SIM_IDSTART_IKGROUP				=SIM_IDEND_DISTANCE+1,
		SIM_IDEND_IKGROUP				=SIM_IDSTART_IKGROUP+10000,
		SIM_IDSTART_GCSOBJECT			=SIM_IDEND_IKGROUP+1,
		SIM_IDEND_GCSOBJECT				=SIM_IDSTART_GCSOBJECT+10000,
		SIM_IDSTART_LUASCRIPT			=SIM_IDEND_GCSOBJECT+1,
		SIM_IDEND_LUASCRIPT				=SIM_IDSTART_LUASCRIPT+10000,
		SIM_IDSTART_2DELEMENT			=SIM_IDEND_LUASCRIPT+1,
		SIM_IDEND_2DELEMENT				=SIM_IDSTART_2DELEMENT+10000,
		SIM_IDSTART_PATHPLANNINGTASK	=SIM_IDEND_2DELEMENT+1,
		SIM_IDEND_PATHPLANNINGTASK		=SIM_IDSTART_PATHPLANNINGTASK+10000,
		SIM_IDSTART_GEOMETRIC_OLD		=SIM_IDEND_PATHPLANNINGTASK+1,
		SIM_IDEND_GEOMETRIC_OLD			=SIM_IDSTART_GEOMETRIC_OLD+100000,
		SIM_IDSTART_TEXTURE				=SIM_IDEND_GEOMETRIC_OLD+1,
		SIM_IDEND_TEXTURE				=SIM_IDSTART_TEXTURE+100000,
		SIM_IDSTART_MOTIONPLANNINGTASK	=SIM_IDEND_TEXTURE+1,
		SIM_IDEND_MOTIONPLANNINGTASK	=SIM_IDSTART_MOTIONPLANNINGTASK+10000,
		SIM_IDSTART_DYNMATERIAL			=SIM_IDEND_MOTIONPLANNINGTASK+1,
		SIM_IDEND_DYNMATERIAL			=SIM_IDSTART_DYNMATERIAL+10000,
};
